import type { LanguageCode } from '../../i18n';

export const FOOTER_ABOUT_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  id: {
    'About Us':'About Us',
    'SYS STREAM adalah platform live, social interaction, dan game/event yang menghubungkan streamer dengan komunitas secara real-time.':'SYS STREAM adalah platform live, social interaction, dan game/event yang menghubungkan streamer dengan komunitas secara real-time.',
    'Official Streamer Partner':'Official Streamer Partner',
    'SYS STREAM bekerja sama dengan streamer terpilih. Official Streamer Partner menggunakan akun platform mereka untuk membuat dan mengelola room sesuai hak akses yang diberikan.':'SYS STREAM bekerja sama dengan streamer terpilih. Official Streamer Partner menggunakan akun platform mereka untuk membuat dan mengelola room sesuai hak akses yang diberikan.'
  },
  en: {
    'About Us':'About Us',
    'SYS STREAM adalah platform live, social interaction, dan game/event yang menghubungkan streamer dengan komunitas secara real-time.':'SYS STREAM is a live, social interaction, and game/event platform connecting streamers with communities in real time.',
    'Official Streamer Partner':'Official Streamer Partner',
    'SYS STREAM bekerja sama dengan streamer terpilih. Official Streamer Partner menggunakan akun platform mereka untuk membuat dan mengelola room sesuai hak akses yang diberikan.':'SYS STREAM works with selected streamers. Official Streamer Partners use their platform accounts to create and manage rooms according to their assigned permissions.'
  },
  es: {
    'About Us':'Sobre nosotros',
    'SYS STREAM adalah platform live, social interaction, dan game/event yang menghubungkan streamer dengan komunitas secara real-time.':'SYS STREAM es una plataforma de directos, interacción social y juegos/eventos que conecta a streamers con comunidades en tiempo real.',
    'Official Streamer Partner':'Socio Oficial de Streamers',
    'SYS STREAM bekerja sama dengan streamer terpilih. Official Streamer Partner menggunakan akun platform mereka untuk membuat dan mengelola room sesuai hak akses yang diberikan.':'SYS STREAM trabaja con streamers seleccionados. Los socios oficiales utilizan sus cuentas para crear y gestionar salas según los permisos asignados.'
  },
  pt: {
    'About Us':'Sobre nós',
    'SYS STREAM adalah platform live, social interaction, dan game/event yang menghubungkan streamer dengan komunitas secara real-time.':'A SYS STREAM é uma plataforma de lives, interação social e jogos/eventos que conecta streamers e comunidades em tempo real.',
    'Official Streamer Partner':'Parceiro Oficial de Streamers',
    'SYS STREAM bekerja sama dengan streamer terpilih. Official Streamer Partner menggunakan akun platform mereka untuk membuat dan mengelola room sesuai hak akses yang diberikan.':'A SYS STREAM trabalha com streamers selecionados. Os parceiros oficiais usam suas contas para criar e gerenciar salas conforme as permissões atribuídas.'
  },
  zh: {
    'About Us':'关于我们',
    'SYS STREAM adalah platform live, social interaction, dan game/event yang menghubungkan streamer dengan komunitas secara real-time.':'SYS STREAM 是一个直播、社交互动及游戏/活动平台，让主播与社区实时连接。',
    'Official Streamer Partner':'官方主播合作伙伴',
    'SYS STREAM bekerja sama dengan streamer terpilih. Official Streamer Partner menggunakan akun platform mereka untuk membuat dan mengelola room sesuai hak akses yang diberikan.':'SYS STREAM 与精选主播合作。官方主播合作伙伴使用平台账号，根据分配的权限创建和管理直播间。'
  },
  ja: {
    'About Us':'私たちについて',
    'SYS STREAM adalah platform live, social interaction, dan game/event yang menghubungkan streamer dengan komunitas secara real-time.':'SYS STREAMは、ストリーマーとコミュニティをリアルタイムでつなぐライブ配信・ソーシャル交流・ゲーム/イベントプラットフォームです。',
    'Official Streamer Partner':'公式ストリーマーパートナー',
    'SYS STREAM bekerja sama dengan streamer terpilih. Official Streamer Partner menggunakan akun platform mereka untuk membuat dan mengelola room sesuai hak akses yang diberikan.':'SYS STREAMは選定されたストリーマーと提携しています。公式ストリーマーパートナーは、付与された権限に従ってアカウントからルームを作成・管理します。'
  },
  ko: {
    'About Us':'회사 소개',
    'SYS STREAM adalah platform live, social interaction, dan game/event yang menghubungkan streamer dengan komunitas secara real-time.':'SYS STREAM은 스트리머와 커뮤니티를 실시간으로 연결하는 라이브, 소셜 인터랙션 및 게임/이벤트 플랫폼입니다.',
    'Official Streamer Partner':'공식 스트리머 파트너',
    'SYS STREAM bekerja sama dengan streamer terpilih. Official Streamer Partner menggunakan akun platform mereka untuk membuat dan mengelola room sesuai hak akses yang diberikan.':'SYS STREAM은 선정된 스트리머와 협력합니다. 공식 스트리머 파트너는 부여된 권한에 따라 플랫폼 계정으로 룸을 만들고 관리합니다.'
  },
  ar: {
    'About Us':'من نحن',
    'SYS STREAM adalah platform live, social interaction, dan game/event yang menghubungkan streamer dengan komunitas secara real-time.':'SYS STREAM هي منصة للبث المباشر والتفاعل الاجتماعي والألعاب/الفعاليات تربط منشئي البث بالمجتمعات في الوقت الفعلي.',
    'Official Streamer Partner':'شريك البث الرسمي',
    'SYS STREAM bekerja sama dengan streamer terpilih. Official Streamer Partner menggunakan akun platform mereka untuk membuat dan mengelola room sesuai hak akses yang diberikan.':'تتعاون SYS STREAM مع منشئي بث مختارين. يستخدم شركاء البث الرسميون حساباتهم لإنشاء الغرف وإدارتها وفق الصلاحيات الممنوحة لهم.'
  }
};
export const STREAMER_FOOTER_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  id: {
    'Untuk Streamer':'Untuk Streamer','Streamer yang ingin bekerja sama dengan SYS STREAM dapat menghubungi tim platform untuk proses seleksi dan kerja sama.':'Streamer yang ingin bekerja sama dengan SYS STREAM dapat menghubungi tim platform untuk proses seleksi dan kerja sama.','Cara kerja & setting streamer':'Cara kerja & setting streamer','Aktivasi':'Aktivasi','Buat Live Room':'Buat Live Room','Setting streaming':'Setting streaming','Mulai live':'Mulai live','Kelola room':'Kelola room','Keamanan':'Keamanan','Akun harus disetujui sebagai Official Streamer Partner oleh Admin/Owner sebelum dapat membuat Live Room.':'Akun harus disetujui sebagai Official Streamer Partner oleh Admin/Owner sebelum dapat membuat Live Room.','Masuk ke Live Room, buat room dengan judul dan deskripsi, lalu room menjadi milik akun streamer tersebut.':'Masuk ke Live Room, buat room dengan judul dan deskripsi, lalu room menjadi milik akun streamer tersebut.','Di kontrol streamer, buat Live Input Cloudflare lalu salin RTMPS Server dan Stream Key ke OBS. Gunakan Service: Custom.':'Di kontrol streamer, buat Live Input Cloudflare lalu salin RTMPS Server dan Stream Key ke OBS. Gunakan Service: Custom.','Klik Start Streaming di OBS, kemudian periksa status streaming pada room. Video produksi akan tampil setelah stream aktif.':'Klik Start Streaming di OBS, kemudian periksa status streaming pada room. Video produksi akan tampil setelah stream aktif.','Pemilik room dapat memantau peserta, chat, like, dan aktivitas live. Data peserta harus berasal dari pengguna yang benar-benar bergabung.':'Pemilik room dapat memantau peserta, chat, like, dan aktivitas live. Data peserta harus berasal dari pengguna yang benar-benar bergabung.','Jangan membagikan Stream Key. Jika Stream Key bocor, buat ulang Live Input agar kredensial lama tidak dapat digunakan.':'Jangan membagikan Stream Key. Jika Stream Key bocor, buat ulang Live Input agar kredensial lama tidak dapat digunakan.'
  },
  en: {
    'Untuk Streamer':'For Streamers','Streamer yang ingin bekerja sama dengan SYS STREAM dapat menghubungi tim platform untuk proses seleksi dan kerja sama.':'Streamers who want to work with SYS STREAM can contact the platform team for selection and partnership.','Cara kerja & setting streamer':'How streamer setup works','Aktivasi':'Activation','Buat Live Room':'Create Live Room','Setting streaming':'Streaming setup','Mulai live':'Go live','Kelola room':'Manage room','Keamanan':'Security','Akun harus disetujui sebagai Official Streamer Partner oleh Admin/Owner sebelum dapat membuat Live Room.':'Your account must be approved as an Official Streamer Partner by an Admin/Owner before you can create a Live Room.','Masuk ke Live Room, buat room dengan judul dan deskripsi, lalu room menjadi milik akun streamer tersebut.':'Open Live Room, create a room with a title and description, and the room becomes owned by your streamer account.','Di kontrol streamer, buat Live Input Cloudflare lalu salin RTMPS Server dan Stream Key ke OBS. Gunakan Service: Custom.':'In streamer controls, create a Cloudflare Live Input, then copy the RTMPS Server and Stream Key into OBS. Use Service: Custom.','Klik Start Streaming di OBS, kemudian periksa status streaming pada room. Video produksi akan tampil setelah stream aktif.':'Click Start Streaming in OBS, then check the room streaming status. Production video appears when the stream is active.','Pemilik room dapat memantau peserta, chat, like, dan aktivitas live. Data peserta harus berasal dari pengguna yang benar-benar bergabung.':'The room owner can monitor participants, chat, likes, and live activity. Participants must come from users who actually joined the room.','Jangan membagikan Stream Key. Jika Stream Key bocor, buat ulang Live Input agar kredensial lama tidak dapat digunakan.':'Never share your Stream Key. If it is exposed, create a new Live Input so the old credentials cannot be used.'
  },
  es: {
    'Untuk Streamer':'Para Streamers','Streamer yang ingin bekerja sama dengan SYS STREAM dapat menghubungi tim platform untuk proses seleksi dan kerja sama.':'Los streamers que quieran colaborar con SYS STREAM pueden contactar al equipo de la plataforma para el proceso de selección y colaboración.','Cara kerja & setting streamer':'Cómo funciona y configuración del streamer','Aktivasi':'Activación','Buat Live Room':'Crear Live Room','Setting streaming':'Configuración de streaming','Mulai live':'Iniciar directo','Kelola room':'Gestionar sala','Keamanan':'Seguridad','Akun harus disetujui sebagai Official Streamer Partner oleh Admin/Owner sebelum dapat membuat Live Room.':'La cuenta debe ser aprobada como Official Streamer Partner por un Admin/Owner antes de crear una Live Room.','Masuk ke Live Room, buat room dengan judul dan deskripsi, lalu room menjadi milik akun streamer tersebut.':'Entra en Live Room, crea una sala con título y descripción y la sala pasará a ser propiedad de tu cuenta de streamer.','Di kontrol streamer, buat Live Input Cloudflare lalu salin RTMPS Server dan Stream Key ke OBS. Gunakan Service: Custom.':'En los controles del streamer, crea un Live Input de Cloudflare y copia el RTMPS Server y Stream Key en OBS. Usa Service: Custom.','Klik Start Streaming di OBS, kemudian periksa status streaming pada room. Video produksi akan tampil setelah stream aktif.':'Pulsa Start Streaming en OBS y comprueba el estado de la transmisión en la sala. El vídeo de producción aparecerá cuando la transmisión esté activa.','Pemilik room dapat memantau peserta, chat, like, dan aktivitas live. Data peserta harus berasal dari pengguna yang benar-benar bergabung.':'El propietario puede supervisar participantes, chat, me gusta y actividad en directo. Los participantes deben ser usuarios que realmente se hayan unido a la sala.','Jangan membagikan Stream Key. Jika Stream Key bocor, buat ulang Live Input agar kredensial lama tidak dapat digunakan.':'No compartas el Stream Key. Si se expone, crea un nuevo Live Input para invalidar las credenciales anteriores.'
  },
  pt: {
    'Untuk Streamer':'Para Streamers','Streamer yang ingin bekerja sama dengan SYS STREAM dapat menghubungi tim platform untuk proses seleksi dan kerja sama.':'Streamers que desejam trabalhar com a SYS STREAM podem entrar em contato com a equipe da plataforma para seleção e parceria.','Cara kerja & setting streamer':'Como funciona e configuração do streamer','Aktivasi':'Ativação','Buat Live Room':'Criar Live Room','Setting streaming':'Configuração de streaming','Mulai live':'Entrar ao vivo','Kelola room':'Gerenciar sala','Keamanan':'Segurança','Akun harus disetujui sebagai Official Streamer Partner oleh Admin/Owner sebelum dapat membuat Live Room.':'A conta deve ser aprovada como Official Streamer Partner por um Admin/Owner antes de criar uma Live Room.','Masuk ke Live Room, buat room dengan judul dan deskripsi, lalu room menjadi milik akun streamer tersebut.':'Entre na Live Room, crie uma sala com título e descrição e ela ficará vinculada à sua conta de streamer.','Di kontrol streamer, buat Live Input Cloudflare lalu salin RTMPS Server dan Stream Key ke OBS. Gunakan Service: Custom.':'Nos controles do streamer, crie um Live Input da Cloudflare e copie o RTMPS Server e a Stream Key para o OBS. Use Service: Custom.','Klik Start Streaming di OBS, kemudian periksa status streaming pada room. Video produksi akan tampil setelah stream aktif.':'Clique em Start Streaming no OBS e verifique o status da transmissão na sala. O vídeo de produção aparecerá quando a transmissão estiver ativa.','Pemilik room dapat memantau peserta, chat, like, dan aktivitas live. Data peserta harus berasal dari pengguna yang benar-benar bergabung.':'O proprietário pode acompanhar participantes, chat, curtidas e atividade ao vivo. Os participantes devem ser usuários que realmente entraram na sala.','Jangan membagikan Stream Key. Jika Stream Key bocor, buat ulang Live Input agar kredensial lama tidak dapat digunakan.':'Nunca compartilhe a Stream Key. Se ela for exposta, crie um novo Live Input para invalidar as credenciais antigas.'
  },
  zh: {
    'Untuk Streamer':'主播专区','Streamer yang ingin bekerja sama dengan SYS STREAM dapat menghubungi tim platform untuk proses seleksi dan kerja sama.':'希望与 SYS STREAM 合作的主播可以联系平台团队进行审核与合作。','Cara kerja & setting streamer':'主播工作流程与设置','Aktivasi':'启用','Buat Live Room':'创建直播间','Setting streaming':'直播设置','Mulai live':'开始直播','Kelola room':'管理直播间','Keamanan':'安全','Akun harus disetujui sebagai Official Streamer Partner oleh Admin/Owner sebelum dapat membuat Live Room.':'账号必须先获得管理员/所有者批准成为官方主播合作伙伴，才能创建直播间。','Masuk ke Live Room, buat room dengan judul dan deskripsi, lalu room menjadi milik akun streamer tersebut.':'进入直播间，填写标题和描述创建房间，房间将归该主播账号所有。','Di kontrol streamer, buat Live Input Cloudflare lalu salin RTMPS Server dan Stream Key ke OBS. Gunakan Service: Custom.':'在主播控制区创建 Cloudflare Live Input，然后将 RTMPS Server 和 Stream Key 填入 OBS，服务选择 Custom。','Klik Start Streaming di OBS, kemudian periksa status streaming pada room. Video produksi akan tampil setelah stream aktif.':'在 OBS 点击开始推流，然后检查直播间状态。直播激活后才会显示正式视频。','Pemilik room dapat memantau peserta, chat, like, dan aktivitas live. Data peserta harus berasal dari pengguna yang benar-benar bergabung.':'房间所有者可以查看参与者、聊天、点赞和直播活动。参与者数据必须来自实际加入房间的用户。','Jangan membagikan Stream Key. Jika Stream Key bocor, buat ulang Live Input agar kredensial lama tidak dapat digunakan.':'请勿分享 Stream Key。如发生泄露，请重新创建 Live Input，使旧凭证失效。'
  },
  ja: {
    'Untuk Streamer':'ストリーマー向け','Streamer yang ingin bekerja sama dengan SYS STREAM dapat menghubungi tim platform untuk proses seleksi dan kerja sama.':'SYS STREAMとの提携を希望するストリーマーは、審査・提携についてプラットフォームチームへお問い合わせください。','Cara kerja & setting streamer':'ストリーマーの仕組みと設定','Aktivasi':'有効化','Buat Live Room':'Live Roomを作成','Setting streaming':'配信設定','Mulai live':'配信開始','Kelola room':'ルーム管理','Keamanan':'セキュリティ','Akun harus disetujui sebagai Official Streamer Partner oleh Admin/Owner sebelum dapat membuat Live Room.':'Live Roomを作成するには、Admin/OwnerからOfficial Streamer Partnerとして承認される必要があります。','Masuk ke Live Room, buat room dengan judul dan deskripsi, lalu room menjadi milik akun streamer tersebut.':'Live Roomを開き、タイトルと説明を入力してルームを作成すると、そのルームはストリーマーアカウントの所有になります。','Di kontrol streamer, buat Live Input Cloudflare lalu salin RTMPS Server dan Stream Key ke OBS. Gunakan Service: Custom.':'ストリーマー設定でCloudflare Live Inputを作成し、RTMPS ServerとStream KeyをOBSへ入力します。ServiceはCustomを選択してください。','Klik Start Streaming di OBS, kemudian periksa status streaming pada room. Video produksi akan tampil setelah stream aktif.':'OBSで配信開始をクリックし、ルームの配信状態を確認します。配信が有効になると本番映像が表示されます。','Pemilik room dapat memantau peserta, chat, like, dan aktivitas live. Data peserta harus berasal dari pengguna yang benar-benar bergabung.':'ルーム所有者は参加者、チャット、いいね、配信アクティビティを確認できます。参加者は実際にルームへ参加したユーザーのみ表示されます。','Jangan membagikan Stream Key. Jika Stream Key bocor, buat ulang Live Input agar kredensial lama tidak dapat digunakan.':'Stream Keyを共有しないでください。漏洩した場合はLive Inputを再作成し、古い認証情報を無効化してください。'
  },
  ko: {
    'Untuk Streamer':'스트리머 안내','Streamer yang ingin bekerja sama dengan SYS STREAM dapat menghubungi tim platform untuk proses seleksi dan kerja sama.':'SYS STREAM과 협업을 원하는 스트리머는 플랫폼 팀에 문의하여 심사 및 파트너십을 진행할 수 있습니다.','Cara kerja & setting streamer':'스트리머 운영 및 설정 방법','Aktivasi':'활성화','Buat Live Room':'Live Room 만들기','Setting streaming':'스트리밍 설정','Mulai live':'라이브 시작','Kelola room':'룸 관리','Keamanan':'보안','Akun harus disetujui sebagai Official Streamer Partner oleh Admin/Owner sebelum dapat membuat Live Room.':'Live Room을 만들려면 먼저 Admin/Owner의 Official Streamer Partner 승인을 받아야 합니다.','Masuk ke Live Room, buat room dengan judul dan deskripsi, lalu room menjadi milik akun streamer tersebut.':'Live Room에 들어가 제목과 설명을 입력해 룸을 만들면 해당 룸은 스트리머 계정의 소유가 됩니다.','Di kontrol streamer, buat Live Input Cloudflare lalu salin RTMPS Server dan Stream Key ke OBS. Gunakan Service: Custom.':'스트리머 제어 화면에서 Cloudflare Live Input을 만든 후 RTMPS Server와 Stream Key를 OBS에 입력하세요. Service는 Custom을 선택합니다.','Klik Start Streaming di OBS, kemudian periksa status streaming pada room. Video produksi akan tampil setelah stream aktif.':'OBS에서 Start Streaming을 누른 뒤 룸의 스트리밍 상태를 확인하세요. 스트림이 활성화되면 실제 영상이 표시됩니다.','Pemilik room dapat memantau peserta, chat, like, dan aktivitas live. Data peserta harus berasal dari pengguna yang benar-benar bergabung.':'룸 소유자는 참가자, 채팅, 좋아요 및 라이브 활동을 확인할 수 있습니다. 참가자는 실제로 룸에 참여한 사용자만 표시됩니다.','Jangan membagikan Stream Key. Jika Stream Key bocor, buat ulang Live Input agar kredensial lama tidak dapat digunakan.':'Stream Key를 공유하지 마세요. 유출된 경우 Live Input을 새로 만들어 기존 인증 정보를 무효화하세요.'
  },
  ar: {
    'Untuk Streamer':'للمُنشئين','Streamer yang ingin bekerja sama dengan SYS STREAM dapat menghubungi tim platform untuk proses seleksi dan kerja sama.':'يمكن لمنشئي البث الراغبين في التعاون مع SYS STREAM التواصل مع فريق المنصة لإجراءات الاختيار والشراكة.','Cara kerja & setting streamer':'طريقة عمل وإعدادات المُنشئ','Aktivasi':'التفعيل','Buat Live Room':'إنشاء غرفة بث مباشر','Setting streaming':'إعداد البث','Mulai live':'بدء البث','Kelola room':'إدارة الغرفة','Keamanan':'الأمان','Akun harus disetujui sebagai Official Streamer Partner oleh Admin/Owner sebelum dapat membuat Live Room.':'يجب اعتماد الحساب كشريك بث رسمي من قِبل Admin/Owner قبل إنشاء غرفة بث مباشر.','Masuk ke Live Room, buat room dengan judul dan deskripsi, lalu room menjadi milik akun streamer tersebut.':'ادخل إلى Live Room وأنشئ غرفة بعنوان ووصف، وستصبح الغرفة مملوكة لحساب المُنشئ.','Di kontrol streamer, buat Live Input Cloudflare lalu salin RTMPS Server dan Stream Key ke OBS. Gunakan Service: Custom.':'من لوحة تحكم المُنشئ، أنشئ Cloudflare Live Input ثم انسخ RTMPS Server وStream Key إلى OBS واختر Service: Custom.','Klik Start Streaming di OBS, kemudian periksa status streaming pada room. Video produksi akan tampil setelah stream aktif.':'اضغط Start Streaming في OBS ثم تحقق من حالة البث داخل الغرفة. سيظهر الفيديو الفعلي بعد تفعيل البث.','Pemilik room dapat memantau peserta, chat, like, dan aktivitas live. Data peserta harus berasal dari pengguna yang benar-benar bergabung.':'يمكن لمالك الغرفة متابعة المشاركين والدردشة والإعجابات ونشاط البث. يجب أن تكون بيانات المشاركين من مستخدمين انضموا فعليًا إلى الغرفة.','Jangan membagikan Stream Key. Jika Stream Key bocor, buat ulang Live Input agar kredensial lama tidak dapat digunakan.':'لا تشارك Stream Key. إذا تم كشفه، أنشئ Live Input جديدًا لإبطال بيانات الاعتماد القديمة.'
  }
};
