import React,{useEffect,useMemo,useState} from "react";
import {Mail,RefreshCw,Send,Check,Archive,Inbox,Link2,ExternalLink,Eye,EyeOff,Paperclip,Clock,UserRound,ShieldAlert} from "lucide-react";

type Attachment={filename?:string;name?:string;contentType?:string;content_type?:string;size?:number;url?:string;downloadUrl?:string;download_url?:string;[key:string]:any};
type Msg={id:string;messageId:string|null;threadId:string;direction:string;mailbox:string;fromEmail:string;fromName:string;toEmail:string;subject:string;textBody:string;htmlBody:string;status:string;receivedAt:number;createdAt?:number;attachments:Attachment[]};
type MailLink={url:string;label:string;host:string;path:string;sensitive:boolean};
const API="/api/admin/email-inbox";
const MAILBOXES=["","admin@sysstreamer.asia","marketing@sysstreamer.asia","support@sysstreamer.asia"];
const decodeEntities=(s:string)=>s.replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#x2F;/gi,"/");
function extractLinks(m:Msg):MailLink[]{
 const html=String(m.htmlBody||"");
 const source=html+"\n"+String(m.textBody||"");
 const found:{url:string;label:string}[]=[];
 const anchor=/<a\b[^>]*href\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))[^>]*>([\s\S]*?)<\/a\s*>/gi;
 let match:RegExpExecArray|null;
 while((match=anchor.exec(html))!==null){
  const url=decodeEntities(match[1]||match[2]||match[3]||"").replace(/\\\//g,"/");
  const label=decodeEntities(String(match[4]||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim());
  if(/^https?:\/\//i.test(url))found.push({url,label:label||url});
 }
 const plain=source.match(/https?:\/\/[^\s"'<>\\]+/gi)||[];
 for(const raw of plain){const url=decodeEntities(raw.replace(/\\\//g,"/").replace(/[),.;]+$/,""));if(/^https?:\/\//i.test(url))found.push({url,label:url});}
 const seen=new Set<string>();
 return found.flatMap(item=>{try{const u=new URL(item.url);if(!["http:","https:"].includes(u.protocol))return[];const key=u.href;if(seen.has(key))return[];seen.add(key);const sensitive=/(token|code|otp|pin|secret|auth|key|session|ticket|signature|password|verify|confirm|one.time|login)/i.test(u.href)||[...u.searchParams.keys()].some(k=>/(token|code|otp|pin|secret|auth|key|session|ticket|signature|password|verify|confirm)/i.test(k));return[{url:u.href,label:item.label,host:u.hostname,path:u.pathname,sensitive}];}catch{return[];}});
}
function safeBody(m:Msg){if(m.textBody?.trim())return m.textBody;return String(m.htmlBody||"").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/[ \t\r\n]+/g," ").trim();}
function formatDate(v:number){return v?new Date(v*1000).toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"}):"Tanggal tidak tersedia";}
function maskedUrl(raw:string){try{const u=new URL(raw);for(const k of [...u.searchParams.keys()])if(/token|code|otp|pin|secret|auth|key|session|ticket|signature|password|verify|confirm/i.test(k))u.searchParams.set(k,"[disamarkan]");return u.href;}catch{return raw;}}
function attachmentName(a:Attachment){return String(a.filename||a.name||"Lampiran");}
function attachmentSize(a:Attachment){const n=Number(a.size||0);return n>0?n<1024?n+" B":n<1024*1024?(n/1024).toFixed(1)+" KB":(n/1024/1024).toFixed(1)+" MB":"";}

export default function EmailInboxPanel(){
 const [mailbox,setMailbox]=useState(""),[messages,setMessages]=useState<Msg[]>([]),[selected,setSelected]=useState<Msg|null>(null),[thread,setThread]=useState<Msg[]>([]);
 const [reply,setReply]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [revealed,setRevealed]=useState<Record<string,boolean>>({});
 const request=async(url=API,options:RequestInit={})=>{const r=await fetch(url,{...options,credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json",...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.error||"Request gagal.");return d};
 const load=async()=>{try{setError("");const q=mailbox?"?mailbox="+encodeURIComponent(mailbox):"";const d=await request(API+q);setMessages(d.messages||[])}catch(e:any){setError(e?.message||"Gagal memuat inbox.")}};
 useEffect(()=>{void load()},[mailbox]);
 const open=async(m:Msg)=>{setSelected(m);setRevealed({});try{const d=await request(API+"?id="+encodeURIComponent(m.id));setThread(d.messages||[]);if(m.status==="unread"){await request(API,{method:"PATCH",body:JSON.stringify({id:m.id,status:"read"})});m.status="read";}}catch(e:any){setError(e?.message||"Gagal membuka email.")}};
 const sendReply=async()=>{if(!selected||!reply.trim())return;setBusy(true);setError("");setMessage("");try{await request(API,{method:"POST",body:JSON.stringify({action:"reply",id:selected.id,text:reply.trim()})});setReply("");setMessage("Balasan berhasil dikirim.");await open(selected);await load()}catch(e:any){setError(e?.message||"Gagal mengirim balasan.")}finally{setBusy(false)}};
 const mark=async(status:string)=>{if(!selected)return;try{await request(API,{method:"PATCH",body:JSON.stringify({id:selected.id,status})});await load();setSelected({...selected,status})}catch(e:any){setError(e?.message||"Gagal memperbarui status.")}};
 const inbound=messages.filter(m=>m.direction==="inbound");
 const currentLinks=useMemo(()=>thread.map(m=>({message:m,links:extractLinks(m)})).filter(x=>x.links.length>0),[thread]);
 const allAttachments=thread.flatMap(m=>(m.attachments||[]).map((a,i)=>({a,key:m.id+"-"+i,message:m})));
 return <div className="space-y-5">
  <section className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-5 flex items-start justify-between gap-4"><div className="flex gap-3"><Inbox className="w-5 h-5 text-cyan-400 mt-0.5"/><div><h2 className="font-bold">Customer Email Inbox</h2><p className="text-xs text-slate-400 mt-1">Email masuk ke admin, marketing, dan support disimpan di D1 dan dapat dibaca serta dibalas dari dashboard. Detail tautan, konfirmasi, dan lampiran ditampilkan di bawah isi email.</p></div></div><button onClick={()=>void load()} className="p-2 rounded-lg border border-slate-700" title="Muat ulang"><RefreshCw className="w-4 h-4"/></button></section>
  {error&&<div className="rounded-xl border border-red-500/20 bg-red-500/10 text-red-300 text-xs p-3">{error}</div>}
  {message&&<div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 text-emerald-300 text-xs p-3">{message}</div>}
  <div className="flex flex-wrap gap-2">{MAILBOXES.map(m=><button key={m||"all"} onClick={()=>setMailbox(m)} className={"px-3 py-2 rounded-lg text-xs font-bold border "+(mailbox===m?"bg-amber-500 text-slate-950 border-amber-500":"border-slate-700 text-slate-400")}>{m||"Semua"} {m?"("+inbound.filter(x=>x.mailbox===m&&x.status==="unread").length+")":""}</button>)}</div>
  <div className="grid xl:grid-cols-[420px_minmax(0,1fr)] gap-5">
   <section className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden"><div className="p-4 border-b border-slate-800 text-sm font-bold">{inbound.length} email masuk</div><div className="max-h-[650px] overflow-y-auto divide-y divide-slate-800">{inbound.map(m=><button key={m.id} onClick={()=>void open(m)} className={"w-full text-left p-4 hover:bg-slate-800/70 "+(selected?.id===m.id?"bg-slate-800":"")}><div className="flex items-center justify-between gap-2"><span className={"text-sm truncate "+(m.status==="unread"?"font-black":"font-semibold")}>{m.fromName||m.fromEmail}</span><span className="text-[10px] text-slate-500">{formatDate(m.receivedAt)}</span></div><div className="text-xs text-cyan-400 mt-1">{m.mailbox}</div><div className={"text-xs mt-2 truncate "+(m.status==="unread"?"text-slate-200":"text-slate-400")}>{m.subject||"(Tanpa subjek)"}</div><div className="text-[11px] text-slate-500 mt-1 truncate">{safeBody(m)}</div></button>)}{!inbound.length&&<div className="p-10 text-center text-sm text-slate-500">Belum ada email masuk.</div>}</div></section>
   <section className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden min-h-[500px]">{!selected?<div className="h-full flex items-center justify-center text-sm text-slate-500"><Mail className="w-5 h-5 mr-2"/>Pilih email untuk membaca.</div>:
    <div><div className="p-5 border-b border-slate-800"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold text-lg">{selected.subject||"(Tanpa subjek)"}</h2><div className="text-xs text-slate-400 mt-2">Dari: <span className="text-slate-200">{selected.fromName?selected.fromName+" ":""}&lt;{selected.fromEmail}&gt;</span></div><div className="text-xs text-slate-400 mt-1">Ke: <span className="text-slate-200">{selected.toEmail||selected.mailbox}</span></div><div className="text-xs text-slate-500 mt-1 flex items-center gap-1"><Clock className="w-3 h-3"/>{formatDate(selected.receivedAt)} · Kotak: {selected.mailbox}</div></div><div className="flex gap-2"><button onClick={()=>void mark("read")} className="p-2 rounded-lg border border-slate-700" title="Tandai sudah dibaca"><Check className="w-4 h-4"/></button><button onClick={()=>void mark("archived")} className="p-2 rounded-lg border border-slate-700" title="Arsipkan"><Archive className="w-4 h-4"/></button></div></div></div>
      <div className="p-5 max-h-[560px] overflow-y-auto space-y-4">{thread.map(m=><div key={m.id} className={"rounded-xl border p-4 "+(m.direction==="outbound"?"border-amber-500/20 bg-amber-500/5":"border-slate-800 bg-slate-950/60")}><div className="flex flex-wrap justify-between gap-2 text-xs font-bold mb-3"><span className="flex items-center gap-1"><UserRound className="w-3 h-3"/>{m.direction==="outbound"?"SYS STREAM":(m.fromName||m.fromEmail)} · {m.direction==="outbound"?"Terkirim":"Masuk"}</span><span className="text-slate-500">{formatDate(m.receivedAt)}</span></div><div className="text-[11px] text-slate-500 mb-2">Dari: {m.fromEmail} · Ke: {m.toEmail||m.mailbox}</div><div className="whitespace-pre-wrap break-words text-sm leading-6">{safeBody(m)||"(Isi teks tidak tersedia)"}</div>{(m.attachments||[]).length>0&&<div className="mt-4 border-t border-slate-800 pt-3"><div className="text-xs font-bold flex items-center gap-2 mb-2"><Paperclip className="w-4 h-4"/>Lampiran ({m.attachments.length})</div><div className="space-y-2">{m.attachments.map((a,i)=>{const href=a.downloadUrl||a.download_url||a.url;return <div key={m.id+"-att-"+i} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-800 p-3"><div><div className="text-sm">{attachmentName(a)}</div><div className="text-xs text-slate-500">{a.contentType||a.content_type||"Jenis file tidak diketahui"} {attachmentSize(a)?"· "+attachmentSize(a):""}</div></div>{href&&/^https:\/\//i.test(href)&&<a className="text-xs text-cyan-400 underline" href={href} target="_blank" rel="noopener noreferrer">Buka lampiran</a>}</div>})}</div></div>}</div>)}
      <section className="rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-4"><div className="flex items-center gap-2 font-bold text-sm"><Link2 className="w-4 h-4 text-cyan-400"/>Detail tautan dalam email</div><p className="text-xs text-slate-400 mt-1">Tautan konfirmasi, verifikasi, login, dan tautan biasa yang ditemukan pada isi HTML/teks email. Parameter rahasia disamarkan secara default.</p>{currentLinks.length===0?<div className="text-xs text-slate-500 mt-3">Tidak ditemukan tautan pada isi email yang tersimpan.</div>:<div className="space-y-4 mt-4">{currentLinks.map(({message:m,links},mi)=><div key={m.id} className="space-y-2"><div className="text-xs font-bold text-slate-300">{m.direction==="outbound"?"Email balasan":"Email masuk"}: {m.subject||"(Tanpa subjek)"}</div>{links.map((l,li)=>{const key=m.id+"-"+li,show=!!revealed[key];return <div key={key} className="rounded-lg border border-slate-800 bg-slate-950/70 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0 flex-1"><div className="text-xs text-cyan-300 break-all">{l.label!==l.url?l.label:"Tautan "+(li+1)}</div><div className="text-xs text-slate-500 mt-1 break-all">{l.host}{l.path}</div><div className="text-xs text-slate-300 mt-2 break-all">{l.sensitive&&!show?maskedUrl(l.url):l.url}</div></div>{l.sensitive&&<span className="shrink-0 rounded-md bg-amber-500/10 text-amber-300 border border-amber-500/20 px-2 py-1 text-[10px] flex items-center gap-1"><ShieldAlert className="w-3 h-3"/>Sensitif</span>}</div><div className="flex flex-wrap gap-2 mt-3">{l.sensitive&&<button onClick={()=>setRevealed(s=>({...s,[key]:!s[key]}))} className="rounded-lg border border-slate-700 px-3 py-2 text-xs flex items-center gap-1">{show?<EyeOff className="w-3 h-3"/>:<Eye className="w-3 h-3"/>}{show?"Samarkan URL":"Tampilkan URL penuh"}</button>}<a className="rounded-lg border border-slate-700 px-3 py-2 text-xs flex items-center gap-1 text-cyan-300" href={l.url} target="_blank" rel="noopener noreferrer" onClick={e=>{if(l.sensitive&&!window.confirm("Tautan ini mungkin berisi token login atau konfirmasi yang bersifat pribadi. Lanjutkan hanya jika Anda mempercayai email dan domain tujuan."))e.preventDefault();}}><ExternalLink className="w-3 h-3"/>Buka tautan</a></div></div>})}</div>)}</div>}</section>
      {allAttachments.length>0&&<section className="rounded-xl border border-slate-800 p-4"><div className="font-bold text-sm flex items-center gap-2"><Paperclip className="w-4 h-4"/>Ringkasan lampiran thread ({allAttachments.length})</div><div className="text-xs text-slate-400 mt-2">{allAttachments.map(({a,key,message:m})=>attachmentName(a)+" · "+m.fromEmail).join(" | ")}</div></section>}
      </div>
      <div className="p-5 border-t border-slate-800"><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={5} placeholder="Tulis balasan customer..." className="w-full rounded-xl bg-slate-950 border border-slate-700 p-4 text-sm"/><div className="flex justify-end mt-3"><button disabled={busy||!reply.trim()} onClick={()=>void sendReply()} className="px-5 py-3 rounded-xl bg-amber-500 text-slate-950 font-extrabold flex items-center gap-2 disabled:opacity-50"><Send className="w-4 h-4"/>{busy?"Mengirim...":"Balas Customer"}</button></div></div>
    </div>}
   </section>
  </div>
 </div>;
}
