import React,{useEffect,useMemo,useState} from "react";
import {Mail,Send,Save,RefreshCw,Eye,History,Users,CheckCircle2,XCircle,ChevronRight} from "lucide-react";

type Sender={id:string;email:string;displayName:string;purpose:string;active:boolean};
type Campaign={id:string;name:string;subject:string;fromEmail:string;fromName:string;audienceType:string;status:string;totalRecipients:number;sentCount:number;failedCount:number;createdAt:number;sentAt:number|null};
const API="/api/admin/email-campaigns",SENDER_API="/api/admin/email-senders";
function esc(v:string){return v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function plainToHtml(v:string){return esc(v).replace(/\n/g,"<br/>");}
function fmt(ts:number|null){return ts?new Date(ts*1000).toLocaleString("id-ID"):"-";}
export default function EmailCampaignPanel(){
 const [senders,setSenders]=useState<Sender[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[selected,setSelected]=useState<Campaign|null>(null);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[testRecipient,setTestRecipient]=useState("");
 const [form,setForm]=useState({name:"",fromEmail:"",fromName:"SYS STREAM",subject:"",html:"",text:"",audienceType:"manual",recipients:""});
 const request=async(url:string,options:RequestInit={})=>{const r=await fetch(url,{...options,credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.error||"Request gagal.");return d};
 const load=async()=>{try{setError("");const [s,c]=await Promise.all([request(SENDER_API),request(API)]);const active=(s.senders||[]).filter((x:Sender)=>x.active);setSenders(active);setCampaigns(c.campaigns||[]);if(!form.fromEmail&&active.length){const preferred=active.find((x:Sender)=>x.purpose==="marketing")||active[0];setForm(f=>({...f,fromEmail:preferred.email,fromName:preferred.displayName||"SYS STREAM"}));}}catch(e:any){setError(e?.message||"Gagal memuat data campaign.")}};
 useEffect(()=>{void load()},[]);
 const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));const previewHtml=useMemo(()=>form.html||plainToHtml(form.text),[form.html,form.text]);
 const create=async(send:boolean)=>{setBusy(true);setError("");setMessage("");try{const d=await request(API,{method:"POST",body:JSON.stringify({action:"create",...form})});if(send){const r=await request(API,{method:"POST",body:JSON.stringify({action:"send",id:d.campaign.id})});setMessage(r.message||"Campaign selesai dikirim.");}else setMessage("Draft campaign tersimpan.");setForm(f=>({...f,name:"",subject:"",html:"",text:"",recipients:""}));await load();}catch(e:any){setError(e?.message||"Gagal menyimpan campaign.")}finally{setBusy(false)}};
 const sendExisting=async(c:Campaign)=>{if(!confirm("Kirim campaign ini sekarang ke semua penerima?"))return;setBusy(true);setError("");setMessage("");try{const d=await request(API,{method:"POST",body:JSON.stringify({action:"send",id:c.id})});setMessage(d.message||"Campaign selesai.");await load()}catch(e:any){setError(e?.message||"Gagal mengirim campaign.")}finally{setBusy(false)}};
 const test=async()=>{if(!testRecipient.trim()){setError("Masukkan email penerima test.");return}if(!form.fromEmail||!form.subject||!previewHtml){setError("Sender, subject dan isi email wajib diisi.");return}setBusy(true);setError("");setMessage("");try{const d=await request(API,{method:"POST",body:JSON.stringify({action:"test",recipient:testRecipient,fromEmail:form.fromEmail,fromName:form.fromName,subject:form.subject,html:previewHtml,text:form.text})});setMessage(d.message||"Test email terkirim.");}catch(e:any){setError(e?.message||"Test email gagal.")}finally{setBusy(false)}};
 return <div className="space-y-6">
  <section className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5"><div className="flex items-start gap-3"><Mail className="w-5 h-5 text-amber-400 mt-0.5"/><div><h2 className="font-bold">Email Campaign</h2><p className="text-xs text-slate-400 mt-1 leading-5">Buat, test, simpan draft dan kirim campaign dari SYS STREAM menggunakan sender Resend yang aktif.</p></div></div></section>
  <section className="grid xl:grid-cols-[minmax(0,1.25fr)_minmax(320px,.75fr)] gap-6">
   <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-5">
    <div className="flex items-center justify-between"><div><h3 className="font-bold">Buat Campaign</h3><p className="text-[11px] text-slate-500 mt-1">Maksimal 500 penerima per campaign.</p></div><button onClick={()=>void load()} className="p-2 rounded-lg border border-slate-700"><RefreshCw className="w-4 h-4"/></button></div>
    <div className="grid md:grid-cols-2 gap-4">
     <Field label="Nama Campaign"><input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="Promo Oktober 2026" className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm"/></Field>
     <Field label="Sender"><select value={form.fromEmail} onChange={e=>set("fromEmail",e.target.value)} className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm">{senders.map(s=><option key={s.id} value={s.email}>{s.displayName} — {s.email}</option>)}</select></Field>
    </div>
    <Field label="Subject"><input value={form.subject} onChange={e=>set("subject",e.target.value)} placeholder="Judul email campaign" className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm"/></Field>
    <div className="grid md:grid-cols-2 gap-4">
     <Field label="Nama pengirim"><input value={form.fromName} onChange={e=>set("fromName",e.target.value)} className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm"/></Field>
     <Field label="Audience"><select value={form.audienceType} onChange={e=>set("audienceType",e.target.value)} className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm"><option value="manual">Email manual</option><option value="users">Semua user SYS STREAM</option></select></Field>
    </div>
    {form.audienceType==="manual"&&<Field label="Penerima"><textarea value={form.recipients} onChange={e=>set("recipients",e.target.value)} placeholder={"customer1@email.com\ncustomer2@email.com\nNama Customer <customer3@email.com>"} className="w-full min-h-28 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm"/></Field>}
    {form.audienceType==="users"&&<div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-xs text-slate-400 flex gap-2"><Users className="w-4 h-4 text-emerald-400 shrink-0"/>Email user production akan disalin ke campaign saat draft dibuat.</div>}
    <div className="grid md:grid-cols-2 gap-4">
     <Field label="HTML Email"><textarea value={form.html} onChange={e=>set("html",e.target.value)} placeholder="<h1>Halo!</h1><p>Isi campaign...</p>" className="w-full min-h-48 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-xs font-mono"/></Field>
     <Field label="Text fallback"><textarea value={form.text} onChange={e=>set("text",e.target.value)} placeholder={"Halo!\n\nIsi email..."} className="w-full min-h-48 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm"/></Field>
    </div>
    <div className="flex flex-col sm:flex-row gap-3"><button disabled={busy} onClick={()=>void create(false)} className="px-4 py-3 rounded-xl border border-slate-700 bg-slate-950 text-xs font-bold flex items-center justify-center gap-2 disabled:opacity-50"><Save className="w-4 h-4"/>Simpan Draft</button><button disabled={busy} onClick={()=>void create(true)} className="px-4 py-3 rounded-xl bg-amber-500 text-slate-950 text-xs font-extrabold flex items-center justify-center gap-2 disabled:opacity-50"><Send className="w-4 h-4"/>Simpan & Kirim</button></div>
    <div className="border-t border-slate-800 pt-5"><div className="flex flex-col sm:flex-row gap-3"><input value={testRecipient} onChange={e=>setTestRecipient(e.target.value)} placeholder="email untuk test" className="flex-1 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm"/><button disabled={busy} onClick={()=>void test()} className="px-4 py-3 rounded-xl border border-slate-700 bg-slate-950 text-xs font-bold flex items-center justify-center gap-2 disabled:opacity-50"><Eye className="w-4 h-4"/>Test Email</button></div></div>
    {message&&<div className="rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 p-3 text-xs">{message}</div>}{error&&<div className="rounded-xl bg-red-500/10 border border-red-500/20 text-red-300 p-3 text-xs">{error}</div>}
   </div>
   <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden"><div className="p-5 border-b border-slate-800 flex items-center gap-2"><Eye className="w-4 h-4 text-amber-400"/><h3 className="font-bold">Preview</h3></div><div className="p-5 bg-white text-slate-900 min-h-[300px] overflow-auto"><div dangerouslySetInnerHTML={{__html:previewHtml}}/></div><div className="p-4 border-t border-slate-800 text-[10px] text-slate-500">Preview hanya untuk admin.</div></div>
  </section>
  <section className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden"><div className="p-5 border-b border-slate-800 flex items-center gap-2"><History className="w-4 h-4 text-amber-400"/><div><h3 className="font-bold">Riwayat Campaign</h3><p className="text-[11px] text-slate-500">{campaigns.length} campaign</p></div></div><div className="divide-y divide-slate-800">{campaigns.map(c=><div key={c.id} className="p-5 flex flex-col lg:flex-row lg:items-center gap-4"><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold truncate">{c.name}</span><Status status={c.status}/></div><div className="text-xs text-slate-400 mt-1 truncate">{c.subject}</div><div className="text-[11px] text-slate-500 mt-2">{c.fromEmail} · {c.totalRecipients} penerima · dibuat {fmt(c.createdAt)}</div></div><div className="flex items-center gap-3 text-xs"><span className="text-emerald-400"><CheckCircle2 className="inline w-3.5 h-3.5 mr-1"/>{c.sentCount}</span><span className="text-red-400"><XCircle className="inline w-3.5 h-3.5 mr-1"/>{c.failedCount}</span>{c.status!=="sent"&&c.status!=="sending"&&<button onClick={()=>void sendExisting(c)} disabled={busy} className="px-3 py-2 rounded-lg bg-amber-500 text-slate-950 font-bold flex items-center gap-1 disabled:opacity-50"><Send className="w-3.5 h-3.5"/>Kirim</button>}<button onClick={()=>setSelected(c)} className="px-3 py-2 rounded-lg border border-slate-700 text-xs flex items-center gap-1"><ChevronRight className="w-3.5 h-3.5"/>Detail</button></div></div>)}{!campaigns.length&&<div className="p-10 text-center text-sm text-slate-500">Belum ada campaign.</div>}</div></section>
  {selected&&<CampaignDetail campaign={selected} onClose={()=>setSelected(null)}/>}
 </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="block text-xs font-semibold text-slate-400 mb-2">{label}</span>{children}</label>}
function Status({status}:{status:string}){const cls=status==="sent"?"bg-emerald-500/10 text-emerald-400":status==="partial"?"bg-amber-500/10 text-amber-400":status==="failed"?"bg-red-500/10 text-red-400":"bg-slate-800 text-slate-400";return <span className={"text-[10px] rounded-full px-2 py-1 "+cls}>{status.toUpperCase()}</span>}
function CampaignDetail({campaign,onClose}:{campaign:Campaign;onClose:()=>void}){const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true);useEffect(()=>{(async()=>{try{const r=await fetch(API+"?id="+encodeURIComponent(campaign.id),{credentials:"same-origin"});const d=await r.json();if(d.success)setData(d)}finally{setLoading(false)}})()},[campaign.id]);return <div className="fixed inset-0 z-50 bg-black/70 p-4 flex items-center justify-center"><div className="w-full max-w-3xl max-h-[90vh] overflow-auto bg-slate-900 border border-slate-700 rounded-2xl"><div className="p-5 border-b border-slate-800 flex items-center justify-between"><div><h3 className="font-bold">{campaign.name}</h3><p className="text-xs text-slate-500">{campaign.subject}</p></div><button onClick={onClose} className="p-2 rounded-lg border border-slate-700">×</button></div>{loading?<div className="p-10 text-center text-slate-500">Memuat...</div>:<div className="p-5"><div className="grid grid-cols-3 gap-3 mb-5"><Metric label="Total" value={data?.campaign?.totalRecipients||0}/><Metric label="Terkirim" value={data?.campaign?.sentCount||0}/><Metric label="Gagal" value={data?.campaign?.failedCount||0}/></div><div className="space-y-2">{(data?.recipients||[]).map((r:any)=><div key={r.id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-950 border border-slate-800 p-3 text-xs"><div className="truncate">{r.email}</div><Status status={r.status}/></div>)}</div></div>}</div></div>}
function Metric({label,value}:{label:string;value:any}){return <div className="rounded-xl bg-slate-950 border border-slate-800 p-3 text-center"><div className="text-[10px] text-slate-500 uppercase">{label}</div><div className="font-black mt-1">{value}</div></div>}
