import React,{useEffect,useState} from "react";
import { Mail,Plus,Power,Send,Trash2,Pencil,X,History,CheckCircle2,XCircle,RefreshCw } from "lucide-react";

type Sender={id:string;email:string;displayName:string;purpose:string;active:boolean;createdAt:number;updatedAt:number};
type EmailCampaign={id:string;name:string;subject:string;fromEmail:string;status:string;totalRecipients:number;sentCount:number;failedCount:number;createdAt:number;sentAt:number|null};
const API="/api/admin/email-senders";
const CAMPAIGN_API="/api/admin/email-campaigns";
function fmt(ts:number|null){return ts?new Date(ts*1000).toLocaleString("id-ID"):"-";}
const PURPOSES=[["general","Umum"],["automatic","Email otomatis"],["admin","Administrasi"],["marketing","Campaign / Marketing"],["support","Bantuan / Support"]];

export default function EmailSendersPanel(){
 const [senders,setSenders]=useState<Sender[]>([]),[campaigns,setCampaigns]=useState<EmailCampaign[]>([]),[form,setForm]=useState({email:"",displayName:"SYS STREAM",purpose:"general"}),[editing,setEditing]=useState<string|null>(null);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[testRecipient,setTestRecipient]=useState("");
 const request=async(options:RequestInit={})=>{const response=await fetch(API,{...options,credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw new Error(data.error||"Request gagal.");return data};
 const load=async()=>{try{setError("");const [data,campaignData]=await Promise.all([request(),fetch(CAMPAIGN_API,{credentials:"same-origin"}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.error||"Gagal memuat riwayat email.");return d})]);setSenders(data.senders||[]);setCampaigns((campaignData.campaigns||[]).filter((c:EmailCampaign)=>c.sentCount>0||c.failedCount>0||["sent","partial","failed","sending"].includes(c.status)))}catch(e:any){setError(e?.message||"Gagal memuat email sender.")}};
 useEffect(()=>{void load()},[]);
 const reset=()=>{setEditing(null);setForm({email:"",displayName:"SYS STREAM",purpose:"general"})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");setMessage("");try{if(editing){await request({method:"PATCH",body:JSON.stringify({id:editing,displayName:form.displayName,purpose:form.purpose})});setMessage("Alamat pengirim berhasil diperbarui.")}else{await request({method:"POST",body:JSON.stringify({action:"create",...form})});setMessage("Alamat pengirim berhasil ditambahkan.")}reset();await load()}catch(e:any){setError(e?.message||"Gagal menyimpan sender.")}finally{setBusy(false)}};
 const edit=(s:Sender)=>{setEditing(s.id);setForm({email:s.email,displayName:s.displayName,purpose:s.purpose});setMessage("");setError("")};
 const toggle=async(s:Sender)=>{setBusy(true);setError("");setMessage("");try{await request({method:"PATCH",body:JSON.stringify({id:s.id,active:!s.active,displayName:s.displayName,purpose:s.purpose})});await load();setMessage(s.active?"Sender dinonaktifkan.":"Sender diaktifkan.")}catch(e:any){setError(e?.message||"Gagal mengubah status sender.")}finally{setBusy(false)}};
 const remove=async(s:Sender)=>{if(!confirm(`Hapus sender ${s.email}?`))return;setBusy(true);setError("");setMessage("");try{const response=await fetch(`${API}?id=${encodeURIComponent(s.id)}`,{method:"DELETE",credentials:"same-origin"});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw new Error(data.error||"Gagal menghapus sender.");await load();setMessage("Sender berhasil dihapus.")}catch(e:any){setError(e?.message||"Gagal menghapus sender.")}finally{setBusy(false)}};
 const test=async(s:Sender)=>{const recipient=testRecipient.trim();if(!recipient){setError("Masukkan email penerima test terlebih dahulu.");return}setBusy(true);setError("");setMessage("");try{const data=await request({method:"POST",body:JSON.stringify({action:"test",id:s.id,recipient})});setMessage(data.message||"Test email berhasil dikirim.")}catch(e:any){setError(e?.message||"Test email gagal.")}finally{setBusy(false)}};
 return <div className="space-y-6">
  <section className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5"><div className="flex items-start gap-3"><Mail className="w-5 h-5 text-amber-400 mt-0.5"/><div><h2 className="font-bold">Email Sender Management</h2><p className="text-xs leading-5 text-slate-400 mt-1">Kelola alamat pengirim SYS STREAM dari dashboard. Domain pengirim harus sudah diverifikasi di Resend. API key Resend tetap berada di Cloudflare dan tidak pernah ditampilkan di dashboard.</p></div></div></section>
  <section className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden"><div className="p-5 border-b border-slate-800 flex items-center justify-between gap-3"><div><h2 className="font-bold">{editing?"Edit Sender":"Tambah Email Pengirim"}</h2><p className="text-[11px] text-slate-500 mt-1">Gunakan @sysstreamer.asia yang sudah diverifikasi di Resend.</p></div>{editing&&<button onClick={reset} className="p-2 rounded-lg border border-slate-700"><X className="w-4 h-4"/></button>}</div>
   <form onSubmit={save} className="p-5 grid md:grid-cols-3 gap-4"><div><label className="block text-xs font-semibold text-slate-400 mb-2">Alamat Email</label><input type="email" disabled={!!editing} value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="noreply@sysstreamer.asia" className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm disabled:opacity-50" required/></div><div><label className="block text-xs font-semibold text-slate-400 mb-2">Nama Pengirim</label><input value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})} placeholder="SYS STREAM" className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm" required/></div><div><label className="block text-xs font-semibold text-slate-400 mb-2">Fungsi</label><select value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})} className="w-full rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm">{PURPOSES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><div className="md:col-span-3 flex items-center gap-3"><button disabled={busy||!form.email||!form.displayName} className="px-5 py-3 rounded-xl bg-amber-500 hover:bg-amber-400 disabled:opacity-50 text-slate-950 font-extrabold flex items-center gap-2"><Plus className="w-4 h-4"/>{busy?"Menyimpan...":editing?"Simpan Perubahan":"Tambah Sender"}</button>{message&&<span className="text-xs text-emerald-400">{message}</span>}{error&&<span className="text-xs text-red-400">{error}</span>}</div></form>
  </section>
  <section className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden"><div className="p-5 border-b border-slate-800"><h2 className="font-bold">Daftar Email Pengirim</h2><p className="text-[11px] text-slate-500 mt-1">{senders.length} sender tersimpan</p></div><div className="p-5 space-y-3">{senders.map(s=><div key={s.id} className="rounded-xl border border-slate-800 bg-slate-950 p-4 flex flex-col xl:flex-row xl:items-center gap-4"><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold truncate">{s.displayName}</span><span className={`text-[10px] rounded-full px-2 py-1 ${s.active?"bg-emerald-500/10 text-emerald-400":"bg-slate-800 text-slate-500"}`}>{s.active?"AKTIF":"NONAKTIF"}</span><span className="text-[10px] rounded-full px-2 py-1 bg-slate-800 text-slate-400">{s.purpose}</span></div><div className="text-sm text-slate-300 mt-1">{s.email}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>edit(s)} disabled={busy} className="px-3 py-2 rounded-lg border border-slate-700 hover:border-amber-500 text-xs flex items-center gap-2"><Pencil className="w-3.5 h-3.5"/> Edit</button><button onClick={()=>void toggle(s)} disabled={busy} className="px-3 py-2 rounded-lg border border-slate-700 hover:border-emerald-500 text-xs flex items-center gap-2"><Power className="w-3.5 h-3.5"/>{s.active?"Nonaktifkan":"Aktifkan"}</button><button onClick={()=>void remove(s)} disabled={busy} className="px-3 py-2 rounded-lg border border-red-500/30 text-red-400 hover:bg-red-500/10 text-xs flex items-center gap-2"><Trash2 className="w-3.5 h-3.5"/>Hapus</button></div></div>)}{!senders.length&&<div className="py-10 text-center text-sm text-slate-500">Belum ada email pengirim. Tambahkan noreply@, admin@, marketing@ atau support@ dari form di atas.</div>}</div>
   {senders.length>0&&<div className="p-5 border-t border-slate-800"><div className="flex flex-col md:flex-row gap-3"><input type="email" value={testRecipient} onChange={e=>setTestRecipient(e.target.value)} placeholder="email penerima untuk test" className="flex-1 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm"/><div className="text-xs text-slate-500 flex items-center">Masukkan penerima lalu pilih sender untuk test.</div></div><div className="mt-3 flex flex-wrap gap-2">{senders.filter(s=>s.active).map(s=><button key={s.id} onClick={()=>void test(s)} disabled={busy||!testRecipient.trim()} className="px-3 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs flex items-center gap-2"><Send className="w-3.5 h-3.5"/>Test dari {s.email}</button>)}</div></div>}
  </section>
  <section className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden">
   <div className="p-5 border-b border-slate-800 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><History className="w-4 h-4 text-amber-400"/><div><h2 className="font-bold">Riwayat Pengiriman Email</h2><p className="text-[11px] text-slate-500 mt-1">Riwayat campaign email resmi beserta jumlah terkirim dan gagal.</p></div></div><button onClick={()=>void load()} className="p-2 rounded-lg border border-slate-700" title="Refresh riwayat"><RefreshCw className="w-4 h-4"/></button></div>
   <div className="divide-y divide-slate-800">{campaigns.map(c=><div key={c.id} className="p-4 flex flex-col md:flex-row md:items-center gap-3"><div className="flex-1 min-w-0"><div className="font-semibold truncate">{c.name}</div><div className="text-xs text-slate-400 mt-1 truncate">{c.subject}</div><div className="text-[11px] text-slate-500 mt-1">{c.fromEmail} · {c.totalRecipients} penerima · {c.sentAt?("dikirim "+fmt(c.sentAt)):("dibuat "+fmt(c.createdAt))}</div></div><div className="flex items-center gap-3 text-xs"><span className="text-emerald-400"><CheckCircle2 className="inline w-3.5 h-3.5 mr-1"/>{c.sentCount} terkirim</span><span className="text-red-400"><XCircle className="inline w-3.5 h-3.5 mr-1"/>{c.failedCount} gagal</span><span className={"rounded-full px-2 py-1 text-[10px] "+(c.status==="sent"?"bg-emerald-500/10 text-emerald-400":c.status==="partial"?"bg-amber-500/10 text-amber-400":c.status==="failed"?"bg-red-500/10 text-red-400":"bg-slate-800 text-slate-400")}>{c.status.toUpperCase()}</span></div></div>)}{!campaigns.length&&<div className="p-10 text-center text-sm text-slate-500">Belum ada riwayat pengiriman campaign.</div>}</div>
  </section>
 </div>;
}
