import React,{useEffect,useState} from "react";
import {Mail,RefreshCw,Send,Check,Archive,Inbox} from "lucide-react";

type Msg={id:string;messageId:string|null;threadId:string;direction:string;mailbox:string;fromEmail:string;fromName:string;toEmail:string;subject:string;textBody:string;htmlBody:string;status:string;receivedAt:number;attachments:any[]};
const API="/api/admin/email-inbox";
const MAILBOXES=["","admin@sysstreamer.asia","marketing@sysstreamer.asia","support@sysstreamer.asia"];

export default function EmailInboxPanel(){
 const [mailbox,setMailbox]=useState(""),[messages,setMessages]=useState<Msg[]>([]),[selected,setSelected]=useState<Msg|null>(null),[thread,setThread]=useState<Msg[]>([]);
 const [reply,setReply]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const request=async(url=API,options:RequestInit={})=>{const r=await fetch(url,{...options,credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.error||"Request gagal.");return d};
 const load=async()=>{try{setError("");const q=mailbox?"?mailbox="+encodeURIComponent(mailbox):"";const d=await request(API+q);setMessages(d.messages||[])}catch(e:any){setError(e?.message||"Gagal memuat inbox.")}};
 useEffect(()=>{void load()},[mailbox]);
 const open=async(m:Msg)=>{setSelected(m);try{const d=await request(API+"?id="+encodeURIComponent(m.id));setThread(d.messages||[]);if(m.status==="unread"){await request(API,{method:"PATCH",body:JSON.stringify({id:m.id,status:"read"})});m.status="read";}}catch(e:any){setError(e?.message||"Gagal membuka email.")}};
 const sendReply=async()=>{if(!selected||!reply.trim())return;setBusy(true);setError("");setMessage("");try{await request(API,{method:"POST",body:JSON.stringify({action:"reply",id:selected.id,text:reply.trim()})});setReply("");setMessage("Balasan berhasil dikirim.");await open(selected);await load()}catch(e:any){setError(e?.message||"Gagal mengirim balasan.")}finally{setBusy(false)}};
 const mark=async(status:string)=>{if(!selected)return;try{await request(API,{method:"PATCH",body:JSON.stringify({id:selected.id,status})});await load();setSelected({...selected,status})}catch(e:any){setError(e?.message||"Gagal memperbarui status.")}};
 const inbound=messages.filter(m=>m.direction==="inbound");
 return <div className="space-y-5">
  <section className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-5 flex items-start justify-between gap-4"><div className="flex gap-3"><Inbox className="w-5 h-5 text-cyan-400 mt-0.5"/><div><h2 className="font-bold">Customer Email Inbox</h2><p className="text-xs text-slate-400 mt-1">Email masuk ke admin, marketing, dan support disimpan di D1 dan dapat dibaca serta dibalas dari dashboard.</p></div></div><button onClick={()=>void load()} className="p-2 rounded-lg border border-slate-700"><RefreshCw className="w-4 h-4"/></button></section>
  {error&&<div className="rounded-xl border border-red-500/20 bg-red-500/10 text-red-300 text-xs p-3">{error}</div>}
  {message&&<div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 text-emerald-300 text-xs p-3">{message}</div>}
  <div className="flex flex-wrap gap-2">{MAILBOXES.map(m=><button key={m||"all"} onClick={()=>setMailbox(m)} className={"px-3 py-2 rounded-lg text-xs font-bold border "+(mailbox===m?"bg-amber-500 text-slate-950 border-amber-500":"border-slate-700 text-slate-400")}>{m||"Semua"} {m ? "("+inbound.filter(x=>x.mailbox===m&&x.status==="unread").length+")" : ""}</button>)}</div>
  <div className="grid xl:grid-cols-[420px_minmax(0,1fr)] gap-5">
   <section className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden"><div className="p-4 border-b border-slate-800 text-sm font-bold">{inbound.length} email masuk</div><div className="max-h-[650px] overflow-y-auto divide-y divide-slate-800">{inbound.map(m=><button key={m.id} onClick={()=>void open(m)} className={"w-full text-left p-4 hover:bg-slate-800/70 "+(selected?.id===m.id?"bg-slate-800":"")}><div className="flex items-center justify-between gap-2"><span className={"text-sm truncate "+(m.status==="unread"?"font-black":"font-semibold")}>{m.fromName||m.fromEmail}</span><span className="text-[10px] text-slate-500">{new Date(m.receivedAt*1000).toLocaleString()}</span></div><div className="text-xs text-cyan-400 mt-1">{m.mailbox}</div><div className={"text-xs mt-2 truncate "+(m.status==="unread"?"text-slate-200":"text-slate-400")}>{m.subject||"(Tanpa subjek)"}</div><div className="text-[11px] text-slate-500 mt-1 truncate">{m.textBody}</div></button>)}{!inbound.length&&<div className="p-10 text-center text-sm text-slate-500">Belum ada email masuk.</div>}</div></section>
   <section className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden min-h-[500px]">{!selected?<div className="h-full flex items-center justify-center text-sm text-slate-500"><Mail className="w-5 h-5 mr-2"/>Pilih email untuk membaca.</div>:
    <div><div className="p-5 border-b border-slate-800"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold text-lg">{selected.subject||"(Tanpa subjek)"}</h2><div className="text-xs text-slate-400 mt-2">Dari: <span className="text-slate-200">{selected.fromEmail}</span></div><div className="text-xs text-slate-500 mt-1">Ke: {selected.mailbox}</div></div><div className="flex gap-2"><button onClick={()=>void mark("read")} className="p-2 rounded-lg border border-slate-700" title="Tandai sudah dibaca"><Check className="w-4 h-4"/></button><button onClick={()=>void mark("archived")} className="p-2 rounded-lg border border-slate-700" title="Arsipkan"><Archive className="w-4 h-4"/></button></div></div></div>
      <div className="p-5 max-h-[430px] overflow-y-auto space-y-4">{thread.map(m=><div key={m.id} className={"rounded-xl border p-4 "+(m.direction==="outbound"?"border-amber-500/20 bg-amber-500/5":"border-slate-800 bg-slate-950/60")}><div className="text-xs font-bold mb-3">{m.direction==="outbound"?"SYS STREAM":"Customer"} · {new Date(m.receivedAt*1000).toLocaleString()}</div><div className="whitespace-pre-wrap text-sm leading-6">{m.textBody}</div></div>)}</div>
      <div className="p-5 border-t border-slate-800"><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={5} placeholder="Tulis balasan customer..." className="w-full rounded-xl bg-slate-950 border border-slate-700 p-4 text-sm"/><div className="flex justify-end mt-3"><button disabled={busy||!reply.trim()} onClick={()=>void sendReply()} className="px-5 py-3 rounded-xl bg-amber-500 text-slate-950 font-extrabold flex items-center gap-2 disabled:opacity-50"><Send className="w-4 h-4"/>{busy?"Mengirim...":"Balas Customer"}</button></div></div>
    </div>}
   </section>
  </div>
 </div>;
}
